export const CREATE_PROJECT = 'CREATE_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const DROP_CURRENT_PROJECT = 'DROP_CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const GET_DICTONARY_KEYS = 'GET_DICTONARY_KEYS';
export const UPDATE_DICTIONARY_PAIR = 'UPDATE_DICTIONARY_PAIR';
