export const CREATE_PROJECT = 'CREATE_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const DROP_PROJECT = 'DROP_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_LOCALE = 'UPDATE_LOCALE';
export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY';
