export const GET_DICTONARY_KEYS = 'GET_DICTONARY_KEYS';
export const CREATE_DICTONARY_KEY = 'CREATE_DICTONARY_KEY';
export const UPDATE_DICTONARY_KEY = 'UPDATE_DICTONARY_KEY';
export const DELETE_DICTONARY_KEY = 'DELETE_DICTONARY_KEY';
