export const GET_DICTONARY_VALUES = 'GET_DICTONARY_VALUES';
export const CREATE_DICTONARY_VALUE = 'CREATE_DICTONARY_VALUE';
export const UPDATE_DICTONARY_VALUE = 'UPDATE_DICTONARY_VALUE';
export const DELETE_DICTONARY_VALUE = 'DELETE_DICTONARY_VALUE';
